# Generated by Django 2.2.6 on 2021-05-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='price',
            field=models.IntegerField(null=True, verbose_name='金額'),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='タイトル'),
        ),
    ]
