# Generated by Django 2.2.6 on 2021-05-08 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20210507_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
    ]
