# Generated by Django 2.2.6 on 2021-05-16 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20210513_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pay_dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 15, 58, 47, 190696, tzinfo=utc), verbose_name='決済日'),
            preserve_default=False,
        ),
    ]
