# Generated by Django 2.2.6 on 2021-05-22 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_topic_pay_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='追加日')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.Category', verbose_name='カテゴリ'),
        ),
    ]
