# Generated by Django 3.1.2 on 2021-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0007_auto_20210605_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='income',
            field=models.IntegerField(default=0, verbose_name='収入'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='spending',
            field=models.IntegerField(default=0, verbose_name='支出'),
        ),
    ]
